### ISSUE TITLE
Apply script without specifying the specific namespace?

### ISSUE THREAD

**Issue by Gittekken** [rwynn/monstache#55] opened 2018-03-23 03:07 UTC
Hi,

Here is my question. I have multiple incoming MongoDB collections being generated in which I do not know the specific names to. I would like to write a script that adds or deletes parts of the name to all of the namespaces. I know in compose transporter you can just apply a javascript Transform without specifying the specific namespace to change. I would like to know how to go about solving this problem in monstache.

Thanks
Ken

**Comment by rwynn** [comment] 2018-03-23 11:04
I think currently you can only do this with a Golang plugin. A Golang plugin gets all ops sent to one Map function. 

All JavaScript mappers currently work on a namespace. I can probably add a global JavaScript mapper.

**Comment by rwynn** [comment] 2018-03-23 22:17
@Gittekken, just pushed a fix for this, but not part of a release yet.  You would need to use go get.

You can now use a script without a namespace also.  This global script will be called for all collections.  The `doc` will be the first argument and the `namespace` will be the second argument.  This function is called before a script with an explicit namespace if one exists.

**Comment by Gittekken** [comment] 2018-03-24 10:26
Thank you very much @rwynn for changing it to be global. The main problem is actually changing the names from mongodb to a different name for the elastic search index. 

[[script]]
# Gives me "_index":"undefined pizza" 
script = """
module.exports = function(doc) {
doc._meta_monstache = {index: doc.index + " pizza"};
return doc;
}
"""

How to use [[script]] if I can’t add strings and use replace(). Below is an example of how I would like the index to be changed. 

# Desired Output from: db.collection: theDB.ny_cheese_inProgress to: ES_index: pizza.ny_cheese_made

-Thanks again
Ken

**Comment by Gittekken** [comment] 2018-03-24 10:28
sorry, did not mean to add the huge text.

**Comment by rwynn** [comment] 2018-03-24 12:29
The mongodb namespace is passed in as the second argument.

```
script = """
module.exports = function(doc, ns) {
// at this point ns would be theDB.ny_cheese_inProgress
var index = "pizza." + ns.split(".")[1].replace("inProgress", "made");
// index should be pizza.ny_cheese_made
doc._meta_monstache = {index: index};
return doc;
}
"""
```

**Comment by Gittekken** [comment] 2018-03-24 14:20
ohhhhh of course. Beautiful! 

thank you so much
-Ken

**Closed** 2018-03-24 14:20 UTC

**Comment by a-magdy** [comment] 2018-04-17 10:15
Hi,

I tried this in my config, and I find it a nice feature, so I don't have to re-rename my collections

I use only the collection name in elasticsearch, so "db.collection_name" goes to ES as "collection_name"

I used this global script:
```toml
[[script]]
script = """
module.exports = function(doc, ns) {
  doc._meta_monstache = { index: ns.split(".")[1] };
  return doc;
}
"""
```

and I removed my custom [[mapping]] and it worked correctly and the data was sent with the intended names

But then I noticed that an error foreach doc in every collection is logged because of, when I reverted to the old [[mapping]] way and removed the global script the error logs weren't logged, here is one of the errors:

`ERROR 2018/04/17 10:09:15 Unable to save routing info: not authorized on monstache to execute command { update: "meta", updates: [ { q: { _id: "<_db_>.<_collection_name_>.<_document_id_>" }, u: { $set: { routing: "", index: "<_collection_name_>", type: "", parent: "", pipeline: "", db: "<_db_>", namespace: "<_db_._collection_name_>" } }, upsert: true } ], writeConcern: { getLastError: 1 }, ordered: true }`

* I replaced names with `<_ ... _>` in the error

Do you know what would be the cause of that?

Thanks :)

**Comment by rwynn** [comment] 2018-04-17 16:25
Hi @a-magdy,

What is happening is that because you are doing dynamic routing, monstache is attempting to save that dynamic routing state in MongoDB and failing to do so because of permissions.  The user that monstache is connecting with is not able to save documents to the `monstache.meta` collection.  You can enable access to `monstache.meta` for that user to have this error go away.

The reason that monstache is trying to save this information is to support delete document.  Normally, monstache knows how to issue a delete command to Elasticsearch when it detects one in MongoDB.  The oplog in MongoDB will contain just enough information to do so.  The oplog will contain the MongoDB namespace of the document that was deleted and its _id.  By default, monstache indexes _id 1 in namespace `test.test` in MongoDB as document _id 1 in the index `test.test` (so in this case no additional info is needed).  However, when custom routing is performed, the user is able to send that document anywhere in Elasticsearch.   So monstache keeps track of where it was sent in the `monstache.meta` collection in MongoDB and then uses that on deletes to locate the document in Elasticsearch for a precise delete.

The approach has a couple of drawbacks: it requires space in MongoDB and adds extra overhead  for each document.  The advantage is has is precision for deletes.  Monstache started as a sync engine so it has always supported propagating deletes in MongoDB.  However, I've noticed that some users are not too interested in deletes and still have to incur this overhead.

I'm thinking of some ways to overcome this.  One way I can think of is to actually perform an _id `search` in Elasticsearch when a delete happens in MongoDB.  This would alleviate the need to save all this routing state in MongoDB but it also has drawbacks.  Say you had 2 collections in MongoDB with documents that share the same _id `123`.  It would be impossible to precisely delete those documents because an _id `search` in Elasticsearch would return more than 1 document.  

With the current approach this isn't a problem because monstache saves the source namespace and destination index along with the _id.  So, even if you rename it knows where that document ended up in Elasticsearch. 

Another alternative is to enable the user to configure how important delete support is.  It may be that the monstache user does not really care about MongoDB deletes syncing to Elasticsearch and may want to turn off the storage requirements and all overhead associated with keeping that state.

Hope this explains why those upsets are being performed by monstache in the `monstache` db in MongoDB.  Let me know if you have any suggestions around this and how important delete support being handled by monstache is to you.

**Comment by rwynn** [comment] 2018-04-17 21:25
Should have a commit soon that will allow 3 strategies for delete. Stateful, stateless, and ignore. Stateful is the current one that puts any custom user routing info in MongoDB. Stateless stores nothing additional at index time and does an _id term search across all indexes to find the doc. If it finds 1 match it adds that to the bulk for deletion. Ignore doesn’t do anything when docs are deleted from MongoDB.

**Comment by a-magdy** [comment] 2018-04-18 12:27
Hi @rwynn 

Thank you so much for your comprehensive response :) :) 🙏 

Out structure with elasticsearch is stateless, we start the whole search structure with monstache on app startup, so deletion are not that important, also we use, `status` fields to reject/remove items, without actually deleting the document from the database

I tried what you said, about giving the mongodb user I send to monstache access to the `monstache` database in mongodb and it worked, I'll go with that solution until we have these 3 strategies out for deletion.

Again thank you for your great work and support 🥇 🎉 👏

**Comment by rwynn** [comment] 2018-04-18 12:43
Hi @a-magdy 

I just pushed a new version last night with stateless as the new default strategy. I’ve not built the docker images for that yet though. You can give that a try.

**Comment by a-magdy** [comment] 2018-04-18 13:13
Built an image locally and tried it, works like a charm, thank you :) 👍
