### ISSUE TITLE
Change in the way empty arrays are stored in ES

### ISSUE THREAD

**Issue by rdamyon** [rwynn/monstache#288] opened 2019-09-30 16:02 UTC
I've noticed that when upgrading from version 4.17.2 to 14.7.3 empty arrays are now persisted in ES as null rather than empty array objects. From the commit history this doesn't appear to be intentional.

My setup is configured using ES 6.6.1 and Mongo 4.0.10

**Comment by rwynn** [comment] 2019-09-30 19:23
@rdamyon thanks I will add a fix with a test case.  It should be a one line fix based on https://github.com/golang/go/issues/26866.

**Comment by rwynn** [comment] 2019-09-30 20:32
@rdamyon just out of curiosity, how does this difference manifest in Elasticsearch?  

From this link, https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html, it seems that "An empty array [] is treated as a missing field — a field with no values." 

And from this link, https://www.elastic.co/guide/en/elasticsearch/reference/current/null-value.html, it states that "When a field is set to null, (or an empty array or an array of null values) it is treated as though that field has no values".

So is there a material difference caused by this change in behavior?  Are you able to differentiate between fields with empty array vs null or vice-versa?

**Comment by rwynn** [comment] 2019-09-30 20:36
I guess maybe the answer to my question is this "The null_value parameter allows you to replace explicit null values with the specified value so that it can be indexed and searched."  Assuming that only an explicit `null` sent would be able to be replaced using this technique and an empty array would not use the `null_value`?

**Comment by rdamyon** [comment] 2019-10-01 13:17
In my particular case these fields were being stored previously as empty arrays in ES i.e { field : [] } where as after updating these fields would be stored in ES as {field : null}

Perhaps I should harden my application to be able to deal with both options if ES is fairly agnostic about it but the JSON spec definitely differentiates between null and empty and my preference is to always return an empty array for array objects.

For my usecase these aren't fields that are being indexed and searched but just stored in the _source object, so they aren't a field I'm setting a specific null_value for.

Also thanks a lot for the speedy response and fix. Monstache has been super useful for my project!

**Comment by rdamyon** [comment] 2019-10-02 10:09
Just tested 4.19.0 and the empty arrays are back to what I expected however non empty arrays seem to be populated with a null item for every non null item.

i.e. 
`paths: [
null,
null,
"value",
"value" ]`

**Comment by rwynn** [comment] 2019-10-03 19:12
@rdamyon hopefully, this should be fixed now in the latest release.  Let me know if you have any problems with it.

**Closed** 2019-10-08 20:16 UTC
