### ISSUE TITLE
Partial update only

### ISSUE THREAD

**Issue by thomasd3** [rwynn/monstache#132] opened 2018-11-15 13:44 UTC
I have done another test: Mongo and ES with default values.

I have inserted 79913 documents in Mongo
ES shows 15703

Monstache's log doesn't show any error, it is full of lines like I posted below. It ran fine, then.. just stopped and never resumed.

I just restarted the Monstache container, not touching anything else, and it is now continuing the process.

What kind of event could make it believe it is up to date where a restart would behave differently?

> 2018-11-15T04:33:15.813943344Z ,
> 2018-11-15T04:33:15.863602133Z TRACE 2018/11/15 04:33:15 POST /_bulk HTTP/1.1
> ,
> 2018-11-15T04:33:15.863636783Z Host: elasticsearch:9200
> ,
> 2018-11-15T04:33:15.863648604Z User-Agent: elastic/6.2.11 (linux-amd64)
> ,
> 2018-11-15T04:33:15.863659574Z Content-Length: 353
> ,
> 2018-11-15T04:33:15.863670284Z Accept: application/json
> ,
> 2018-11-15T04:33:15.863681165Z Content-Type: application/x-ndjson
> ,
> 2018-11-15T04:33:15.863691950Z Accept-Encoding: gzip
> ,
> 2018-11-15T04:33:15.863702970Z 
> ,
> 2018-11-15T04:33:15.813943344Z ,
> 2018-11-15T04:33:15.863602133Z TRACE 2018/11/15 04:33:15 POST /_bulk HTTP/1.1
> ,
> 2018-11-15T04:33:15.863636783Z Host: elasticsearch:9200
> ,
> 2018-11-15T04:33:15.863648604Z User-Agent: elastic/6.2.11 (linux-amd64)
> ,
> 2018-11-15T04:33:15.863659574Z Content-Length: 353
> ,
> 2018-11-15T04:33:15.863670284Z Accept: application/json
> ,
> 2018-11-15T04:33:15.863681165Z Content-Type: application/x-ndjson
> ,
> 2018-11-15T04:33:15.863691950Z Accept-Encoding: gzip
> ,
> 2018-11-15T04:33:15.863702970Z 
> ,
> 2018-11-15T04:33:15.863713770Z {"index":{"_index":"test.pictures","_id":"6t8Y22YJibT2581XdMqHHeEtQ7rB-sdAY1eZyWNSpJk","_type":"pictureobject","version":6623940778571857932,"version_type":"external"}},
> 2018-11-15T04:33:15.863729797Z {"AlbumId":"ba1219cf-a4ac-48ef-ba44-97ea92acd215","AlbumOffset":1,"CreatedOn":"2018-11-15T04:33:15.779Z","Height":1056,:1280},
> 2018-11-15T04:33:15.863745391Z ,
> 2018-11-15T04:33:15.975347512Z TRACE 2018/11/15 04:33:15 HTTP/1.1 200 OK
> ,
> 2018-11-15T04:33:15.975396401Z Content-Type: application/json; charset=UTF-8
> ,
> 2018-11-15T04:33:15.975409870Z 
> ,
> 2018-11-15T04:33:15.975421687Z {"took":160,"errors":false,"items":[{"index":{"_index":"test.pictures","_type":"pictureobject","_id":"UV5Va08voGCcigueWS33CAAOlVaPzccnGtQ16O748g0","_version":6623940778571857929,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":2773,"_primary_term":1,"status":201}}]},
> 2018-11-15T04:33:15.998852980Z TRACE 2018/11/15 04:33:15 HTTP/1.1 200 OK
> ,
> 2018-11-15T04:33:15.998884665Z Content-Type: application/json; charset=UTF-8
> ,
> 2018-11-15T04:33:15.998901749Z 
> ,
> 2018-11-15T04:33:15.998916722Z {"took":134,"errors":false,"items":[{"index":{"_index":"test.pictures","_type":"pictureobject","_id":"6t8Y22YJibT2581XdMqHHeEtQ7rB-sdAY1eZyWNSpJk","_version":6623940778571857932,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":2886,"_primary_term":1,"status":201}}]},
> 2018-11-15T04:33:16.011857085Z TRACE 2018/11/15 04:33:16 POST /_bulk HTTP/1.1
> ,
> 2018-11-15T04:33:16.011873086Z Host: elasticsearch:9200
> ,
> 2018-11-15T04:33:16.011877574Z User-Agent: elastic/6.2.11 (linux-amd64)
> ,
> 2018-11-15T04:33:16.011881519Z Content-Length: 353
> ,
> 2018-11-15T04:33:16.011885168Z Accept: application/json
> ,
> 2018-11-15T04:33:16.011892067Z Content-Type: application/x-ndjson
> ,
> 2018-11-15T04:33:16.011895881Z Accept-Encoding: gzip
> ,
> 2018-11-15T04:33:16.011899544Z 
> ,
> 2018-11-15T04:33:16.011911735Z {"index":{"_index":"test.pictures","_id":"-6flUZrvARXzfwkpyZGuSZ3Jcjk+s7lIJUG86HucvaI","_type":"pictureobject","version":6623940778571857943,"version_type":"external"}},
> 2018-11-15T04:33:16.011917122Z {"AlbumId":"bdabb811-e0a4-4683-be32-c5f9b0c1c550","AlbumOffset":1,"CreatedOn":"2018-11-15T04:33:15.951Z","Height":1707,:1280},
> 2018-11-15T04:33:16.011922212Z ,
> 2018-11-15T04:33:16.168856954Z TRACE 2018/11/15 04:33:16 HTTP/1.1 200 OK
> ,
> 2018-11-15T04:33:16.168879239Z Content-Type: application/json; charset=UTF-8
> ,
> 2018-11-15T04:33:16.168886263Z 
> ,
> 2018-11-15T04:33:16.168892682Z {"took":155,"errors":false,"items":[{"index":{"_index":"test.pictures","_type":"pictureobject","_id":"-6flUZrvARXzfwkpyZGuSZ3Jcjk+s7lIJUG86HucvaI","_version":6623940778571857943,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":2873,"_primary_term":1,"status":201}}]},
> 2018-11-15T04:33:16.939082838Z TRACE 2018/11/15 04:33:16 POST /_bulk HTTP/1.1
> ,
> 2018-11-15T04:33:16.939114432Z Host: elasticsearch:9200
> ,
> 2018-11-15T04:33:16.939119081Z User-Agent: elastic/6.2.11 (linux-amd64)
> ,
> 2018-11-15T04:33:16.939123031Z Content-Length: 352
> ,
> 2018-11-15T04:33:16.939126620Z Accept: application/json
> ,
> 2018-11-15T04:33:16.939130441Z Content-Type: application/x-ndjson
> ,
> 2018-11-15T04:33:16.939133983Z Accept-Encoding: gzip
> ,
> 2018-11-15T04:33:16.939137506Z 
> ,
> 2018-11-15T04:33:16.939141020Z {"index":{"_index":"test.pictures","_id":"io0YMW+63RHRth+lpSS9ZuFnCyEZBbqhs6RS7o9emoA","_type":"pictureobject","version":6623940782866825221,"version_type":"external"}},
> 2018-11-15T04:33:16.939159386Z {"AlbumId":"bdabb811-e0a4-4683-be32-c5f9b0c1c550","AlbumOffset":2,"CreatedOn":"2018-11-15T04:33:16.842Z","Height":936,:1280},
> 2018-11-15T04:33:16.939166411Z ,
> 2018-11-15T04:33:17.120868582Z TRACE 2018/11/15 04:33:17 HTTP/1.1 200 OK
> ,
> 2018-11-15T04:33:17.120909556Z Content-Type: application/json; charset=UTF-8
> ,
> 2018-11-15T04:33:17.120923217Z 
> ,
> 2018-11-15T04:33:17.120934657Z {"took":180,"errors":false,"items":[{"index":{"_index":"test.pictures","_type":"pictureobject","_id":"io0YMW+63RHRth+lpSS9ZuFnCyEZBbqhs6RS7o9emoA","_version":6623940782866825221,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":2941,"_primary_term":1,"status":201}}]},
> 2018-11-15T04:33:17.390380525Z TRACE 2018/11/15 04:33:17 POST /_bulk HTTP/1.1
> ,
> 2018-11-15T04:33:17.390418980Z Host: elasticsearch:9200
> ,
> 2018-11-15T04:33:17.390428162Z User-Agent: elastic/6.2.11 (linux-amd64)
> ,
> 2018-11-15T04:33:17.390435967Z Content-Length: 353
> ,
> 2018-11-15T04:33:17.390443256Z Accept: application/json
> ,
> 2018-11-15T04:33:17.390450596Z Content-Type: application/x-ndjson
> ,
> 2018-11-15T04:33:17.390457727Z Accept-Encoding: gzip
> ,
> 2018-11-15T04:33:17.390478861Z 
> ,
> 2018-11-15T04:33:17.390486694Z {"index":{"_index":"test.pictures","_id":"rYE331Fy23wLP9PiwkYf86UZ1mQphIBC4wWdg-VqdsY","_type":"pictureobject","version":6623940787161792515,"version_type":"external"}},
> 2018-11-15T04:33:17.390496858Z {"AlbumId":"b9a0522f-4a3e-4cbe-8c18-9a7259097ad5","AlbumOffset":9,"CreatedOn":"2018-11-15T04:33:17.355Z","Height":1690,:1280},

**Comment by thomasd3** [comment] 2018-11-15 14:06
Interesting: after restarting Monstache, it kept running until ES had 42942 documents and it went to sleep again.

The last part the log is:

```
{"took":307,"errors":false,"items":[{"index":{"_index":"test.pictures","_type":"pictureobject","_id":"faiN1zyFvsPFeMuJu5eC94Xaroi4UYqBAGrgOU+DT4U","_version":6624082082995896320,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":4794,"_primary_term":1,"status":201}}]},
Content-Type: application/json; charset=UTF-8


```

So, I just restarted Monstache and.. it keeps going.
There was absolutely no activity on Mongo or ES during that time; the test server is completely idle.

**Comment by rwynn** [comment] 2018-11-15 14:50
During those logs where you just inserting a single document at a time?  Cause normally when you run a `direct-read` it bulks many documents at once.  Your log is showing 1 document inserted at a time.  That would be terrible for performance.

Can you share any overrides to the default config you have made?  And can you enable stats and show the stats when you determine that the sync is not full?

**Comment by thomasd3** [comment] 2018-11-15 14:54
this is my config file:

gzip = true

mongo-url = "mongodb://root-user:****@mongodb:27017"

elasticsearch-urls = ["http://elasticsearch:9200"]

elasticsearch-max-conns = 10
elasticsearch-max-seconds = 1
elasticsearch-max-docs = 1
elasticsearch-max-bytes = 800000

dropped-collections = true
dropped-databases = true

namespace-regex = '^test\.pictures$'
direct-read-namespaces = [ "test.pictures" ]
change-stream-namespaces = [ "test.pictures" ]

verbose = true

enable-http-server = true

[mongo-dial-settings]
ssl = false

[gtm-settings]
channel-size = 50000

[[mapping]]
namespace="test.pictures"
type = "pictureobject"

[[filter]]
namespace = "test.pictures"
script = """
module.exports = function(doc) {
    return (doc.Status == 1);
}
"""

[[script]]
namespace = "test.pictures"
script = """

**Comment by rwynn** [comment] 2018-11-15 14:58
Can you please try with these settings.

```
elasticsearch-max-conns = 3
elasticsearch-max-seconds = 3
elasticsearch-max-bytes = 800000
REMOVE elasticsearch-max-docs = 1 REMOVE
```
The `elasticsearch-max-docs` = 1 is gonna kill your performance.

**Comment by thomasd3** [comment] 2018-11-15 15:04
the difference is night and day! I deleted the ES database and restarted from scratch; it synced the whole thing in seconds!

thanks a lot man, that solved one of my major problems!

**Comment by rwynn** [comment] 2018-11-15 15:16
Glad to hear it.  I was beginning to wonder how I was getting such different results.

**Comment by thomasd3** [comment] 2018-11-16 10:34
I have to re-open this one; the changes you recommended transformed the speed and documents are now indexed super fast, but there was again the problem of Monstache stopping mid process and waiting. Restarting it completed the indexing.

Besides verbose=true that doesn't seem to help us much, is there anything I can enable to see what is happening?

**Comment by rwynn** [comment] 2018-11-16 12:39
By stopping do you mean process is killed or process is running but not doing anything?  

We may want to remove the channel size setting now since that may cause a excessive memory usage. It defaults to 512 but I suggested 50k.

**Comment by thomasd3** [comment] 2018-11-16 12:41
The process is just idle, doesn't us any CPU; no Mongo activity will wake it up; and when I restart it, it carries on like nothing happened.
There is also nothing in the log.

The data going to ES is very small, the DB is < 100mb, it's essentially tag words pointing to guids, so I don't think memory is a factor.

**Comment by rwynn** [comment] 2018-11-16 12:50
That’s a strange one. It’s supposed to continue tailing the oplog after the full direct read sync is done so that any changes on your change-stream-namespace get synced. I’ve never seen it not do that.

**Comment by thomasd3** [comment] 2018-11-16 12:52
It there any way for me to output more log to see what happens, or the internal state?

**Comment by rwynn** [comment] 2018-11-16 12:55
No not really cause it is pretty much stateless. The only thing I can think of would be a filter such as the regex filter or script filter is returning false and monstache is thus ignoring the event. 

Maybe I need to wrap all these filters with logging.

**Comment by thomasd3** [comment] 2018-11-16 12:56
yes, printing what passes by the filter would be good, we'd see right away if the problem is ahead, like connectivity, at the filter, or after.

**Comment by rwynn** [comment] 2018-11-16 15:21
@thomasd3 you mentioned before in this thread that monstache synched the whole collection after fixing the config.  Is this reopen issue that the whole collection only gets synced sometimes?  Or is the issue that after the sync is completed monstache does not keep up with changes?

One thing to ensure is that since you are using change streams you have mongodb set up properly to accommodate this.  This means that you need to have replica sets configured properly.  So something like this in your mongodb config.

```
replication:
  replSetName: rs1
```
Do you have something like this?

**Comment by thomasd3** [comment] 2018-11-16 17:17
At some point it just stops keeping up with the changes and will no resume without a restart.
Once I restart it’ll run fine until, at some point, it stops.

The mongo config is a copy paste from the one in Mobstafhe’s docker-compose.

I haven’t seen any errors in Mongo / ES logs either.

**Comment by rwynn** [comment] 2018-11-16 17:55
hmm, I'm not experiencing the same issue.  Do you have a link to this config?  Are you able replicate it with a minimal config that specifies **only** (1) mongo url (2) elastic url (3) change stream ns and (4) direct read ns?

By the way you don't need `namespace-regex` when you specify change stream ns.  That is because the regex is only useful for **legacy** oplog tailing (pre 3.6 MongoDB) which tails the **entire** oplog.  The legacy mode gets turned off when you use change stream ns since that targets specific collections.

**Comment by rwynn** [comment] 2018-11-16 18:18
If you mean this config...

https://github.com/rwynn/monstache/blob/master/docker/test/monstache.test.config.toml

then yeah, that's not a typical config that you would want to use.  It's designed just for the test to have minimal latency on a couple of changes.  Thus, the max-docs and max-seconds set to 1.  This is just so that the test runs more quickly.  Normally, it's best to not tweak any of the defaults. 

I'll do more testing on the docker compose now that I know that's what you're using.

**Comment by thomasd3** [comment] 2018-11-16 23:14
I have put the contents of my dockerfile here: https://pastebin.com/gjdRNwNH
and the Monstache config file is above, in the thread.

I'm not using the run-test.sh, but I definitely used your config file as a base for mine.

**Comment by rwynn** [comment] 2018-11-17 05:19
I tried to look at this more tonight.  I found that there are some issues with the `change-stream-namespaces` option.  For one thing it doesn't work well with docker-compose since it requires the collection to be created before issuing the `$watch` command.  So you end up getting into race conditions in docker compose between the mongodb setup and monstache issuing the $watch.  If monstache starts before the collection is created then it basically gives up on that change stream.  This is something that I need to work around in the monstache code (if collection not found ping periodically until it exists). 

Some good news is that tailing the oplog collection directly (not using change streams) was working fine for me via docker compose.  So, I would suggest that at least for now you **remove** the `change-stream-namespaces` from your config and **add** a `namespace-regex` to control which collections are watched for changes.

**Comment by thomasd3** [comment] 2018-11-17 14:37
I have seen this issue where, on the initial run, Monstache doesn't find the collection and it will stay idle. Once the collection is created, after I restart Monstache, it works.

I just did the change and remove the *change-stream-namespaces* field. I always had the namespace-regex present however.

So, now the main issue is how to troubleshoot the stops mid-process. As we were discussing before, adding debug logging could help in that direction; unless you spot something dramatically wrong in the config files I sent.

**Comment by rwynn** [comment] 2018-11-17 15:38
Let me know if it still stops mid for you without change streams.

**Comment by rwynn** [comment] 2018-11-19 20:31
@thomasd3 I've been testing this and I think I may have been able to replicate the `stops` mid process.  I think it may have to do with the default timeout settings of `no timeout` and how this affects the mongodb driver.  Can you try the following settings and let me know if they help?

```
[mongo-dial-settings]
read-timeout = 7
write-timeout = 7

[mongo-session-settings]
sync-timeout = 7
````

These are all 0 by default and basically turn off the timeouts in the driver.  But with the defaults I've noticed that the driver gets locked up after a while of usage.  With these timeouts set I see that this lock resolves itself and the processing continues.

**Comment by thomasd3** [comment] 2018-11-19 22:30
Thanks for researching this; I've added these settings and restarted the system. I'll let you know how it goes!

**Comment by rwynn** [comment] 2018-11-20 19:06
@thomasd3 I've just pushed a new release.  Please let me know how that goes. You should be able to use `change-stream-namespaces` with this release.

**Comment by mapshen** [comment] 2018-11-22 12:48
I believe I am have the same issue here: monstache stops midway during direct reads and will resume work after a restart.

I am testing it by running a single container and here is my config:

```
  "MongoURL": "REDACTED",
  "MongoConfigURL": "",
  "MongoPemFile": "",
  "MongoValidatePemFile": true,
  "MongoOpLogDatabaseName": "",
  "MongoOpLogCollectionName": "",
  "MongoDialSettings": {
    "Timeout": 15,
    "Ssl": false,
    "ReadTimeout": 7,
    "WriteTimeout": 7
  },
  "MongoSessionSettings": {
    "SocketTimeout": 0,
    "SyncTimeout": 7
  },
  "GtmSettings": {
    "ChannelSize": 512,
    "BufferSize": 32,
    "BufferDuration": "75ms"
  },
  "AWSConnect": {
    "AccessKey": "",
    "SecretKey": "",
    "Region": ""
  },
  "Logs": {
    "Info": "/monstache/logs/info.log",
    "Warn": "/monstache/logs/warn.log",
    "Error": "/monstache/logs/error.log",
    "Trace": "",
    "Stats": "/monstache/logs/stats.log"
  },
  "GraylogAddr": "",
  "ElasticUrls": [
    "REDACTED"
  ],
  "ElasticUser": "",
  "ElasticPassword": "",
  "ElasticPemFile": "",
  "ElasticValidatePemFile": false,
  "ElasticVersion": "",
  "ResumeName": "apollo",
  "NsRegex": "^db.col",
  "NsDropRegex": "",
  "NsExcludeRegex": "",
  "NsDropExcludeRegex": "",
  "ClusterName": "apollo",
  "Print": true,
  "Version": false,
  "Pprof": false,
  "DisableChangeEvents": false,
  "EnableEasyJSON": false,
  "Stats": true,
  "IndexStats": false,
  "StatsDuration": "",
  "StatsIndexFormat": "monstache.stats.2006-01-02",
  "Gzip": false,
  "Verbose": false,
  "Resume": true,
  "ResumeWriteUnsafe": false,
  "ResumeFromTimestamp": 0,
  "Replay": false,
  "DroppedDatabases": true,
  "DroppedCollections": true,
  "IndexFiles": false,
  "IndexAsUpdate": false,
  "FileHighlighting": false,
  "EnablePatches": false,
  "FailFast": false,
  "IndexOplogTime": false,
  "OplogTsFieldName": "oplog_ts",
  "OplogDateFieldName": "oplog_date",
  "OplogDateFieldFormat": "2006/01/02 15:04:05",
  "ExitAfterDirectReads": false,
  "MergePatchAttr": "json-merge-patches",
  "ElasticMaxConns": 4,
  "ElasticRetry": false,
  "ElasticMaxDocs": -1,
  "ElasticMaxBytes": 8388608,
  "ElasticMaxSeconds": 5,
  "ElasticClientTimeout": 0,
  "ElasticMajorVersion": 0,
  "ElasticMinorVersion": 0,
  "MaxFileSize": 0,
  "ConfigFile": "config.toml",
  "Script": null,
  "Filter": null,
  "Pipeline": null,
  "Mapping": null,
  "Relate": null,
  "FileNamespaces": null,
  "PatchNamespaces": null,
  "Workers": null,
  "Worker": "",
  "ChangeStreamNs": null,
  "DirectReadNs": [
    "db.col1",
    "db.col2",
    "db.col3",
    "db.col4",
    "db.col5",
    "db.col6",
    "db.col7",
    "db.col8",
    "db.col9",
    "db.col10,
    "db.col11"
  ],
  "DirectReadSplitMax": 9,
  "MapperPluginPath": "",
  "EnableHTTPServer": true,
  "HTTPServerAddr": ":8080",
  "TimeMachineNamespaces": null,
  "TimeMachineIndexPrefix": "log",
  "TimeMachineIndexSuffix": "2006-01-02",
  "TimeMachineDirectReads": false,
  "PipeAllowDisk": false,
  "RoutingNamespaces": null,
  "DeleteStrategy": 0,
  "DeleteIndexPattern": "*",
  "FileDownloaders": 0,
  "RelateThreads": 10,
  "PostProcessors": 0,
  "PruneInvalidJSON": true
}
```
None of the 11 indexes's doc counts match the numbers in my collections still even after a few restarts for a small collection that only have 38 documents.

 Wondering if this could be caused by trying reading too many collections directly, which I am testing right now.

**Comment by rwynn** [comment] 2018-11-22 17:13
It would be really great if you could enable web server and Pprof and take a goroutine snapshot when it gets stuck. 

https://stackoverflow.com/questions/19094099/how-to-dump-goroutine-stacktraces

That way could see what is blocking.

**Comment by thomasd3** [comment] 2018-11-22 17:19
With the last changes I did, based on your feedback, I haven't had an issue yet with Monstache being stuck. But I can try to recreate the whole ES db to see if it happens again. Let me know if it could help.

**Comment by mapshen** [comment] 2018-11-23 00:59
@rwynn Sorry I didn't get to this today. Will do it tomorrow and circle back.

**Comment by mapshen** [comment] 2018-11-27 21:38
@rwynn Apologize again for my delayed response. Was totally derailed.

Running it with only 1 direct read ns worked fine with me. And it turned out the root cause was pretty simple, which was overlooked by me. Here is what I found in the `error.log` for example:

```
ERROR 2018/11/26 20:21:13 Bulk response item: {"_index":"index_name","_type":"page","_id":"5a9f1fb11d2fac36fb57d66a","status":429,"error":{"type":"es_rejected_execution_exception","reason":"rejected execution of org.elasticsearch.transport.TransportService$4@5ee642f3 on EsThreadPoolExecutor[bulk, queue capacity = 50, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@4c019222[Running, pool size = 8, active threads = 8, queued tasks = 50, completed tasks = 175630]]"}}
```
All I needed to do to fix this was to bump up the queue size of the `bulk` thread pool as recommended per https://rwynn.github.io/monstache-site/config/#elasticsearch-max-conns.

Thanks for the help!

**Comment by thomasd3** [comment] 2018-11-27 23:57
I have had 200 in mine for a while. I have to report that since the the last update, everything has worked fine!

**Comment by rwynn** [comment] 2018-11-28 00:02
Glad to hear it’s  working better now. I will close this issue now. Please open a new one if you come across something else.

**Closed by rwynn** 2018-11-28 00:02 UTC
