### ISSUE TITLE
Error with direct-read-namespaces with monstache v6.0.8

### ISSUE THREAD

**Issue by botgitfool** [rwynn/monstache#247] opened 2019-06-27 01:14 UTC
Hi
When I put direct-read-namespaces = ["db.doc"] in toml, monstche spit out the following error:-

monstache7    | WARN 2019/06/27 01:03:04 For performance reasons it is recommended to use elasticsearch-max-bytes instead of elasticsearch-max-docs since doc size may vary
monstache7    | INFO 2019/06/27 01:03:04 Started monstache version 6.0.8
monstache7    | INFO 2019/06/27 01:03:04 Successfully connected to MongoDB version 3.4.21
monstache7    | INFO 2019/06/27 01:03:04 Successfully connected to Elasticsearch version 7.1.1
monstache7    | INFO 2019/06/27 01:03:04 Sending systemd READY=1
monstache7    | WARN 2019/06/27 01:03:04 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
monstache7    | INFO 2019/06/27 01:03:04 Starting http server at :8080
monstache7    | panic: runtime error: invalid memory address or nil pointer dereference
monstache7    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xf59589]
monstache7    | 
monstache7    | goroutine 93 [running]:
monstache7    | main.(*indexClient).startReadWait.func1(0xc0004ec540)
monstache7    | 	/app/monstache.go:3743 +0x29
monstache7    | created by main.(*indexClient).startReadWait
monstache7    | 	/app/monstache.go:3742 +0x57
monstache7 exited with code 2

Do you know what might have caused it?
Thank you

**Comment by rwynn** [comment] 2019-06-27 01:42
I'm not sure what would have caused it.  I am not able to reproduce the panic however, I have different versions of MongoDB and Elasticsearch.

```
$ docker run --rm --network host rwynn/monstache:6.0.8 -direct-read-namespace test.test -exit-after-direct-reads -enable-http-server
INFO 2019/06/27 01:39:39 Started monstache version 6.0.8
INFO 2019/06/27 01:39:39 Successfully connected to MongoDB version 4.0.10
INFO 2019/06/27 01:39:39 Successfully connected to Elasticsearch version 7.0.0
INFO 2019/06/27 01:39:39 Listening for events
INFO 2019/06/27 01:39:39 Watching changes on the deployment
INFO 2019/06/27 01:39:39 Direct reads completed
INFO 2019/06/27 01:39:39 Stopping all workers
INFO 2019/06/27 01:39:40 Shutting down
```

Are you using the docker image?  

If using Monstache 6.0.8 with MongoDB pre 3.6 you won't have change streams available in the MongoDB feature set.  You would need to omit `change-stream-namespaces` from your config and set `enable-oplog` to true.  Have you tried that?

If building monstache yourself, what golang version and os?

**Comment by botgitfool** [comment] 2019-06-27 01:48
Hi rwynn,
`change-stream-namespaces` is omitted and `enable-oplog` is set to `true`. I'm using the `build.sh` file to build the plugin and using docker to run monstache. My toml file looks like this

```
mongo-url = ...
elasticsearch-urls = ["http://es7:9600"]
elasticsearch-max-conns = 10
elasticsearch-max-seconds = 10
elasticsearch-max-docs = 1
enable-oplog = true 
namespace-regex = '^sparkstagingstu3\.resources$' 
direct-read-namespaces = ["sparkstagingstu3.resources"] 
```

What's strange is that if I comment out the `direct-read-namespace` monstache does not crash and tails the oplog without issues.

**Comment by rwynn** [comment] 2019-06-27 01:53
Does it panic if you add `direct-read-namespaces` as you have but do not pass the location of the plugin?  Just trying to figure out if maybe the plugin interaction is causing it.

**Comment by botgitfool** [comment] 2019-06-27 01:58
It still crashes even without the plugin file loaded. Maybe it's to do with the combination of ES7 and Mongo 3.x?

**Comment by rwynn** [comment] 2019-06-27 02:10
I think it has to do with -enable-oplog.  Need to look into that switch.

**Comment by rwynn** [comment] 2019-06-27 03:26
@botgitfool  I think those commits fix the issue. Will do a new release later this week.  Thanks for reporting.

**Comment by botgitfool** [comment] 2019-06-27 03:28
If I comment out `enable-oplog` monstache returns the error "Error starting change stream" (even with `change-stream-namespaces` commented out), due to the Mongo version being below 3.6.

**Comment by rwynn** [comment] 2019-06-27 03:33
Yeah, you definitely need `enable-oplog` for your MongoDB version.  It turns out this is actually caused by things being done out of order and a race condition with go routines.

**Comment by rwynn** [comment] 2019-06-27 23:08
@botgitfool this should be fixed now with the latest release.  Please let me know if you have any issues.

**Closed** 2019-07-06 20:54 UTC

**Comment by mowenlong** [comment] 2019-07-11 06:16
INFO 2019/07/11 14:12:05 Started monstache version 5.0.9
INFO 2019/07/11 14:12:05 Successfully connected to MongoDB version 3.2.10
INFO 2019/07/11 14:12:05 Successfully connected to Elasticsearch version 6.8.1
INFO 2019/07/11 14:12:05 Listening for events
INFO 2019/07/11 14:12:05 Watching changes on the deployment
ERROR 2019/07/11 14:12:05 Error starting change stream. Will retry.: Invalid input namespace, admin.
ERROR 2019/07/11 14:12:05 Error starting change stream. Will retry.: Invalid input namespace, admin.

Must the root user?
