### ISSUE TITLE
Not keeping up with the Oplog after a Full Sync

### ISSUE THREAD

**Issue by BrunoPereira** [rwynn/monstache#111] opened 2018-10-11 19:18 UTC
I'm having problems when trying to keep up with the oplog after a full sync.

**Just a Full Sync**
**config.toml:**
direct-read-namespaces = ["my.Recording", "my.User"]
exit-after-direct-reads = true

no problem

**Just keep up with the oplog** 
**config.toml:**
exit-after-direct-reads = false

no problem

**Full Sync + keep up with oplog** <-Problem
**config.toml:**
`&&connection settings

&& connect to MongoDB using the following URL
mongo-url = "mongodb://127.0.0.1:27017"
mongo-config-url = "mongodb://127.0.0.1:27019"
&& connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["http://es:9200"]

&& frequently required settings
&& additionally, if you need to seed an index from a collection and not just listen for changes from the oplog
&& you can copy entire collections from MongoDB to Elasticsearch
direct-read-namespaces = ["my.Recording", "my.User"]
&& do not exit after full-sync, rather continue tailing the oplog
exit-after-direct-reads = false 

&& if you don't want to listen for changes to all collections in MongoDB but only a few
&& e.g. only listen for inserts, updates, deletes, and drops from mydb.mycollection
&& this setting does not initiate a copy, it is a filter on the change listener only
namespace-regex = "^my.(Recording|User)$"

&& When mapping is given monstache will be directed to override the default index and type assigned to documents in Elasticsearch. See the section Index Mapping for more information.
&& ES index starts with test to avoid mappings and pipeline

&& additional settings
workers = ["Tom", "Dick", "Harry"]
&& compress requests to Elasticsearch
gzip = true
&&When stats is true monstache will periodically print statistics accumulated by the indexer
&& generate indexing statistics
stats = true
&& index statistics into Elasticsearch - stdOut instead
&&index-stats = true
&&stats-duration = 30s

&& use 4 go routines concurrently pushing documents to Elasticsearch
elasticsearch-max-conns = 4
&&The number of seconds before a request to Elasticsearch times out
&&elasticsearch-client-timeout = 60
&& don't use this, use elasticsearch-max-bytes instead
&&elasticsearch-max-docs 
&&When elasticsearch-max-bytes is given a bulk index request to Elasticsearch will be forced when a connection buffer reaches the given number of bytes. This setting greatly impacts performance
&&Each connection in elasticsearch-max-conns will flush when its queue gets filled to this size. <- We can have problems here, maybe only 1 connection with a big buffer to avoid concurrency problems
&& when mapping recordings to users and the recording ain't there yet - int (default 8MB as bytes)
elasticsearch-max-bytes=32
&&When elasticsearch-max-seconds is given a bulk index request to Elasticsearch will be forced when a request has not been made in the given number of seconds int (default 1)
elasticsearch-max-seconds=5

&&When elasticseach-retry is true a failed request to Elasticsearch will be retried with an exponential backoff policy. The policy is set with an initial timeout of 50 ms, an exponential factor of 2, and a max wait of 20 seconds.
elasticsearch-retry = true
&& propagate dropped collections in MongoDB as index deletes in Elasticsearch
dropped-collections = false
&& propagate dropped databases in MongoDB as index deletes in Elasticsearch
dropped-databases = false
&& do not start processing at the beginning of the MongoDB oplog
&& if you set the replay to true you may see version conflict messages
&& in the log if you had synced previously. This just means that you are replaying old docs which are already
&& in Elasticsearch with a newer version. Elasticsearch is preventing the old docs from overwriting new ones.
replay = false
&& resume processing from a timestamp saved in a previous run
&& saved in collection monstache.monstache
resume = true
&& do not validate that progress timestamps have been saved
&&Since errors writing the last synched timestamp are only logged by monstache and do not stop execution it's not unreasonable to set this to true to get a speedup.
resume-write-unsafe = true

&& override the name under which resume state is saved (named by worker name)
resume-name = "default"
&& exclude documents whose namespace matches the following pattern
&& we use namespace-regex defined above
&&namespace-exclude-regex = '^mydb\.ignorecollection$'

index-as-update = true
&& enable clustering mode
&& High availability, To be used with multiple processes...
&&cluster-name = 'apollo'

&& print detailed information including request traces
&& DEBUG
&&verbose = true
&& print conf and exit <-DEBUG
&&print-config = true
&& Add this flag to enable an embedded HTTP server at localhost:8080 
enable-http-server = true
&& When pprof is true and the http server is enabled, monstache will make profiling information available.
&& See Profiling for Go for more information. https://artem.krylysov.com/blog/2017/03/13/profiling-and-optimizing-go-web-applications/
pprof = true

&&TOML table (default nil)
&&Allows writing logs to a file using a rolling appender instead of stdout. Supply a file path for each type of log you would like to send to a file.
[logs]
info = "/tmp/logs/file-info.log"
&& warn
&&warn = "/tmp/logs/file-warn.log"
error = "/tmp/logs/file-error.log"
&&  Trace logs are enabled via the verbose option.
&&trace = "/tmp/logs/file-trace.log"
stats= "/tmp/logs/file-stats.log"
`

Can't figure out what I'm doing wrong.....
PS: replaced '#' with && , so when you see && it's actually comments in my conf

**Comment by rwynn** [comment] 2018-10-12 00:43
By not keeping up do you mean that some changes never get to Elasticsearch? Or they get there but too slowly?

Anything interesting in the stats?  Does the number of queued keep going up?  Each worker in the stats should report how long it’s last request took in ms.

**Comment by BrunoPereira** [comment] 2018-10-12 10:30
Sorry, I wasn't clear....
After the Full Sync (and that is done correctly), he says that he's listening to events but he doesn't send a single one to Elastic.

And I know that there's events that he was supposed to processed ....
Right now I'm testing it... so I don't have that many events.
I altered some records on mongo to make sure he needed to sync events.
Below is a sample of the stats ..... This is when he had events to process but no change was done in Elastic
**Stats:**
STATS 2018/10/11 18:59:15 {"Flushed":24,"Committed":31336,"Indexed":0,"Created":0,"Updated":31336,"Deleted":0,"Succeeded":31336,"Failed":0,"Workers":[{"Queued":1,"LastDuration":2000000},{"Queued":1,"LastDuration":5000000},{"Queued":1,"LastDuration":8000000},{"Queued":1,"LastDuration":9000000}]}
STATS 2018/10/11 18:59:18 {"Flushed":24,"Committed":32174,"Indexed":0,"Created":0,"Updated":32174,"Deleted":0,"Succeeded":32172,"Failed":2,"Workers":[{"Queued":1,"LastDuration":3000000},{"Queued":1,"LastDuration":3000000},{"Queued":1,"LastDuration":4000000},{"Queued":1,"LastDuration":3000000}]}
STATS 2018/10/11 18:59:25 {"Flushed":24,"Committed":34545,"Indexed":0,"Created":0,"Updated":34545,"Deleted":0,"Succeeded":34545,"Failed":0,"Workers":[{"Queued":1,"LastDuration":5000000},{"Queued":1,"LastDuration":8000000},{"Queued":1,"LastDuration":6000000},{"Queued":1,"LastDuration":36000000}]}
STATS 2018/10/11 18:59:45 {"Flushed":30,"Committed":38797,"Indexed":0,"Created":0,"Updated":38797,"Deleted":0,"Succeeded":38797,"Failed":0,"Workers":[{"Queued":0,"LastDuration":13000000},{"Queued":0,"LastDuration":10000000},{"Queued":0,"LastDuration":5000000},{"Queued":0,"LastDuration":13000000}]}

**Comment by rwynn** [comment] 2018-10-13 00:19
I tried this today but wasn’t able to replicate. Also do you mean to have this as your regex?

^my\.(Recording|User)$

Have you tried without a regex?

**Comment by rwynn** [comment] 2018-10-13 00:40
You wouldn’t want elasticsearch-max-bytes to be as low as 32. The default is 8000000 for 8mb. 32 would index each doc individually instead of in bulk. You may have had that commented though.

**Comment by BrunoPereira** [comment] 2018-10-14 20:06
Regarding elasticsearch-max-bytes, I read the units wrong, I'll change it.
Regarding the regex, no I didn't tried without it... I have more DB on that mongo and I don't want monstache to catch those events.

Either way, monstache works great when only doing the full sync or only keeping up with the oplog

**Comment by rwynn** [comment] 2018-10-14 20:19
A bad workers config could cause some events to be ignored. By bad config I mean that there is a not a monstache process running for each of the eligible workers defined. I would also try without using workers.

**Comment by rwynn** [comment] 2018-10-15 14:15
@BrunoPereira I tried this again today on a sharded cluster, with workers, and a regex, and a full sync.  I couldn't replicate the issue.  After the full sync completed I was able to connect to the mongos instance, insert some records, and see the records get indexed into Elasticsearch.  

I did notice the anomoly that only 1 of the monstache processes was handling all of the inserts after the full sync which is something to look into.  The hashing of the mongodb _id field should distribute evenly between the workers.  The changes were not being dropped though.

**Comment by rwynn** [comment] 2018-10-15 14:18
@BrunoPereira I think I found the reason that all records were going to the same worker.  I will add a fix for this.  But I do think the problem was not that changes were being dropped but rather that they were only being handled by one of the available workers.

**Comment by BrunoPereira** [comment] 2018-10-22 16:02
@rwynn Just tested today (and I did a git pull to get the most recent docker image)
Like previously , it did the full sync flawlessly ....
But when trying to keep up with the oplog, it doesn't sync some of the events.
I have configured 2 workers, and I'm running 2 instances, one for each worker.

**Log worker1:**
STATS 2018/10/22 15:48:59 {"Flushed":360,"Committed":25,"Indexed":0,"Created":0,"Updated":20240,"Deleted":0,"Succeeded":20240,"Failed":0,"Workers":[{"Queued":0,"LastDuration":378000000},{"Queued":0,"LastDuration":411000000},{"Queued":0,"LastDuration":334000000},{"Queued":0,"LastDuration":437000000}]}
STATS 2018/10/22 15:49:29 {"Flushed":366,"Committed":25,"Indexed":0,"Created":0,"Updated":20240,"Deleted":0,"Succeeded":20240,"Failed":0,"Workers":[{"Queued":0,"LastDuration":378000000},{"Queued":0,"LastDuration":411000000},{"Queued":0,"LastDuration":334000000},{"Queued":0,"LastDuration":437000000}]}
STATS 2018/10/22 15:49:59 {"Flushed":372,"Committed":25,"Indexed":0,"Created":0,"Updated":20240,"Deleted":0,"Succeeded":20240,"Failed":0,"Workers":[{"Queued":0,"LastDuration":378000000},{"Queued":0,"LastDuration":411000000},{"Queued":0,"LastDuration":334000000},{"Queued":0,"LastDuration":437000000}]}
STATS 2018/10/22 15:50:29 {"Flushed":378,"Committed":25,"Indexed":0,"Created":0,"Updated":20240,"Deleted":0,"Succeeded":20240,"Failed":0,"Workers":[{"Queued":0,"LastDuration":378000000},{"Queued":0,"LastDuration":411000000},{"Queued":0,"LastDuration":334000000},{"Queued":0,"LastDuration":437000000}]}

**Log Worker2:**
STATS 2018/10/22 15:48:18 {"Flushed":361,"Committed":15,"Indexed":0,"Created":0,"Updated":18016,"Deleted":0,"Succeeded":18016,"Failed":0,"Workers":[{"Queued":0,"LastDuration":87000000},{"Queued":0,"LastDuration":116000000},{"Queued":0,"LastDuration":135000000},{"Queued":0,"LastDuration":1317000000}]}
STATS 2018/10/22 15:48:48 {"Flushed":367,"Committed":15,"Indexed":0,"Created":0,"Updated":18016,"Deleted":0,"Succeeded":18016,"Failed":0,"Workers":[{"Queued":0,"LastDuration":87000000},{"Queued":0,"LastDuration":116000000},{"Queued":0,"LastDuration":135000000},{"Queued":0,"LastDuration":1317000000}]}
STATS 2018/10/22 15:49:18 {"Flushed":373,"Committed":15,"Indexed":0,"Created":0,"Updated":18016,"Deleted":0,"Succeeded":18016,"Failed":0,"Workers":[{"Queued":0,"LastDuration":87000000},{"Queued":0,"LastDuration":116000000},{"Queued":0,"LastDuration":135000000},{"Queued":0,"LastDuration":1317000000}]}
STATS 2018/10/22 15:49:48 {"Flushed":379,"Committed":15,"Indexed":0,"Created":0,"Updated":18016,"Deleted":0,"Succeeded":18016,"Failed":0,"Workers":[{"Queued":0,"LastDuration":87000000},{"Queued":0,"LastDuration":116000000},{"Queued":0,"LastDuration":135000000},{"Queued":0,"LastDuration":1317000000}]}
STATS 2018/10/22 15:50:18 {"Flushed":385,"Committed":15,"Indexed":0,"Created":0,"Updated":18016,"Deleted":0,"Succeeded":18016,"Failed":0,"Workers":[{"Queued":0,"LastDuration":87000000},{"Queued":0,"LastDuration":116000000},{"Queued":0,"LastDuration":135000000},{"Queued":0,"LastDuration":1317000000}]}

This logs are from when they are trying to keep up with the oplog.
They basically have very few events in the oplog to sync, so I can't find any reason why they can't sync.
That and I don't see any errors in the logs.
I even have the conf that in case there's an error writing to Elastic Search ("elasticsearch-retry = true
") monstrache retries.

**Comment by rwynn** [comment] 2018-10-22 16:47
Can I see how you are invoking each process and the config file used for each process?  

You are sure `worker` is configured to be different for each process?  If you configure the `workers` to be ["A", "B"] then you need exactly 2 processes with one using `worker` = A and the other using `worker` = B.  Finally, if you had workers = ["A", "B", "C"] but you didn't run a process where worker = C, then it wouldn't work properly.  You need to run a process for all of them.  

Do you have cluster-name defined in either config?  If so, you should remove it.  The reason is that in cluster mode some processes pause and 1 runs.  When the active stops the paused ones resume.  Just want to make sure you are not using cluster mode.  

Are you running Docker with `rwynn/monstache:3.18.3`?

**Comment by BrunoPereira** [comment] 2018-10-22 18:17
docker run --rm -v ~/monstache/:/tmp/ rwynn/monstache:rel3 -f /tmp/config-sharded.toml -mapper-plugin-path /tmp/npvr-plugin.so -worker Harry
docker run --rm -v ~/monstache/:/tmp/ rwynn/monstache:rel3 -f /tmp/config-sharded.toml -mapper-plugin-path /tmp/npvr-plugin.so -worker Tom
**config-sharded.toml**
workers = ["Tom", "Harry"]

2 workers configured and I'm running a process foreach one.

I don't have cluster-name.

And as you can see, I'm running with the latest from rel3, 3.18.3
INFO 2018/10/22 18:16:05 Started monstache version 3.18.3

**Comment by rwynn** [comment] 2018-10-22 18:55
@BrunoPereira the only thing I can think of it that the event is somehow getting dropped in the plugin.  I tried again to replicate this issue and couldn't.  See attached animated gif trying to replicate the issue.  

![monstache-111](https://user-images.githubusercontent.com/260672/47312451-62c69a80-d60a-11e8-98ce-9d44683dc220.gif)

**Comment by BrunoPereira** [comment] 2018-10-23 16:55
@rwynn 
To debug if it was the plugin, I removed the workers from the conf file and run just 1 instance .....
 docker run --rm -v ~/monstache/:/tmp/ rwynn/monstache:rel3 -f /tmp/config-sharded.toml -mapper-plugin-path /tmp/npvr-plugin.so

Like this monstache has no problems in doing the full sync and keeping up with the oplog after.

I've seen your gift... looks like what I'm doing with the workers.... If I didn't tested with just 1 instance I would have to agree with you... that test doesn't find any errors... looks like it's working as intended...

The thing is.... when I add the workers to the conf and have multiple instances running eventually I get a different counts in Mongo and Elastic.

How can I help debug this? 
Right now I have about 40k objects there and my tests consist in modifying/adding/removing about 1k objects.

To do a full disclosure, I'm doing this to replace a similar process I have today, but using mongo-connectors.
From the tests I've done, monstache is a lot better than mongo-connectors, so much so that I might not need workers, I'm just fully testing it....

You did a bang up job with monstache, not only the code, but the doc and the support... I would like to help somehow... maybe figuring up what's happening in this situation....

So.... can you give me tips to help diagnose this? do you want more logs? ....etc....

**Comment by rwynn** [comment] 2018-10-23 17:36
@BrunoPereira the only thing I can think of is to start with the smallest reproducible example. Maybe start with a collection that is empty and then run your script such that it adds/modifies/deletes maybe 10 records.  Obviously you would want to clear the Elasticsearch index before running this.  See if the counts do not match for multiple workers after that.   Increase the complexity of your test until your find a mismatch.  

The workers mode is a filter on the docs processed using a hash ring of the document _id.

https://github.com/serialx/hashring

So when each doc _id is put through the hash ring, the ring should return only 1 of the available workers.  If the current process' worker name is the one returned by the hash ring, then it will be the one to process the doc while the others would ignore it.  That is what I was trying to show in that video where you will notice that as I add documents they are handled by only 1 of the 3 available processes and not the others.

**Comment by rwynn** [comment] 2018-10-23 17:50
You might also try giving a different `resume-name` to each worker.  Maybe match the worker name. I think sharing may be problematic if the processes are started too far from one another.  The second process started might resume in the oplog ahead from where it should.  This would really only be a problem with dropped deletes since you are doing a full sync.

**Comment by BrunoPereira** [comment] 2018-10-24 10:36
@rwynn 
I'm not changing the resume-name... so it's the default, the worker name.

As far as workers starting 2 far apart, I have 2 bash shells with the commands ready and the delay is a mere seconds, just enough time to hit enter one one and change to the other and hit enter again.

I've cleared the Elastic Index before each test...

And I don't get more results in Elastic than in Mongo, I get less results. Maybe when trying to decide what worker should process the even, none is assigned and it gets discarded... I don't know...

I'll test this later....

**Closed** 2019-02-05 17:14 UTC
