### ISSUE TITLE
Error decoding UTC timestamp into gtm.Optime

### ISSUE THREAD

**Issue by nakulm95** [rwynn/monstache#269] opened 2019-08-04 21:50 UTC
Hey Ryan,

Seeing this error pop up after direct reads are done:
INFO 2019/08/03 08:10:04 Direct reads completed
ERROR 2019/08/03 08:10:04 cannot decode UTC datetime into a gtm.Optime

I can't find the exact line but I suspect the error lies somewhere inside saveTimestampFromReplStatus() because this method gets called right after the direct reads are done if resume is set to true (which it is in my case).

Thanks!

**Comment by rwynn** [comment] 2019-08-04 22:08
What version of MongoDB are you running with?  I’ll check it out.

**Comment by rwynn** [comment] 2019-08-04 22:16
Also if you could post the output of the command `db.adminCommand( { replSetGetStatus : 1 } )`.  

Monstache looks to decode a Timestamp from `optimes.lastCommittedOpTime.ts`.  It seems like that was a date in your case.

**Comment by nakulm95** [comment] 2019-08-07 18:48
> What version of MongoDB are you running with? I’ll check it out.

Running a beta version: 4.2.0.



> Also if you could post the output of the command `db.adminCommand( { replSetGetStatus : 1 } )`.
> 
> Monstache looks to decode a Timestamp from `optimes.lastCommittedOpTime.ts`. It seems like that field was a Date instead in this case.

![image](https://user-images.githubusercontent.com/7410988/62649140-25b56580-b909-11e9-9c5d-eae3f6af4c11.png)

**Comment by rwynn** [comment] 2019-08-07 19:54
That looks like what I would expect.  I don't actually get this error message when I tried direct reads with resume on with the latest monstache v6 release.  So not sure why this error message would be popping up for you.  `saveTimestampFromReplStatus` is just there to read the timestamp from the command output and save this in the `monstache` database for resuming later.

**Comment by rwynn** [comment] 2019-08-07 19:59
Oh, I know what the problem is.  It looks like in recent releases that they have added some wall time fields that are not objects but simply dates.  I think the code needs to be updated to account for the fact that the following is now wrong for deserialization:

https://github.com/rwynn/gtm/blob/leafny/gtm.go#L118

Need to change that to map[string]interface{} and then only convert to Timestamp for the single field I need.

**Comment by rwynn** [comment] 2019-08-21 23:35
@nakulm95 this should be fixed in the latest release.  Please let me know if not.

**Closed** 2019-09-02 03:56 UTC
