### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by m3hari** [rwynn/monstache#140] opened 2018-12-07 20:34 UTC
monstache crashs with panic I saved the stack trace.

``` 
panic: send on closed channel

goroutine 136 [running]:
github.com/rwynn/gtm.StartMulti.func3(0xc0007ee330, 0xc0009e8f00, 0xc0009e8fc0)
	/home/vagrant/go/src/github.com/rwynn/gtm/gtm.go:1559 +0x7d
created by github.com/rwynn/gtm.StartMulti
	/home/vagrant/go/src/github.com/rwynn/gtm/gtm.go:1556 +0x359

```

```
panic: send on closed channel

goroutine 125 [running]:
github.com/rwynn/gtm.StartMulti.func3(0xc000b545d0, 0xc000b902a0, 0xc000b90360)
	/home/vagrant/go/src/github.com/rwynn/gtm/gtm.go:1559 +0x7d
created by github.com/rwynn/gtm.StartMulti
	/home/vagrant/go/src/github.com/rwynn/gtm/gtm.go:1556 +0x359
    
./monstache -f config.toml  95.38s user 24.30s system 78% cpu 2:31.75 total
```

Here is my full config
```

# mongo-url="mongodb://dev:1%40w0rdsdev@ahadoo-cluster-shard-00-00-f1nha.mongodb.net:27017,ahadoo-cluster-shard-00-01-f1nha.mongodb.net:27017,ahadoo-cluster-shard-00-02-f1nha.mongodb.net:27017/hipdbv01?ssl=true&replicaSet=ahadoo-cluster-shard-0&authSource=admin&readPreference=nearest"
mongo-url = 'localhost:27018'

# verbose = true
gzip = true
stats = true
index-stats = true
enable-http-server = true
http-server-addr = ":8182"
stats-duration = "5s"
elasticsearch-max-seconds = 5
elasticsearch-max-conns = 10
elasticsearch-max-bytes = 2000000
fail-fast = true

# prune-invalid-json = true
disable-change-events = true

exit-after-direct-reads = true



# Full Sync  
direct-read-namespaces = [
"hipdbv01.Person",
"hipdbv01.SystemActivity",
"hipdbv01.RequestValue",
"hipdbv01.Allocation",
"hipdbv01.Company",
"hahugraduates-db.Student",
"hahugraduates-db.College",
"hahujobs-db.Person",
"hahujobs-db.Company"
]



[[script]]
script = """
module.exports = function(doc, ns) {
    return !!doc._isDeleted ? false : doc;
}
"""


[[script]]
namespace = "hahugraduates-db.Student"
path = "./student.middleware.js"

[[script]]
namespace = "hipdbv01.Person"
path = "./person.middleware.js"


[[script]]
namespace = "hipdbv01.SystemActivity"
path = "./system-activity.middleware.js"

[[script]]
namespace = "hipdbv01.Allocation"
path = "./allocation.middleware.js"

[[script]]
namespace = "hipdbv01.RequestValue"
path = "./person-requests.middleware.js"



# Logging conf
[logs]
info = "./info.log"
warn = "./warn.log"
error = "./error.log"
stats = "./stats.log"
trace = "./trace.log"
```

**Version**
INFO 2018/12/07 23:24:28 Started monstache version 4.12.3
INFO 2018/12/07 23:24:28 Successfully connected to MongoDB version 4.0.4
INFO 2018/12/07 23:24:28 Successfully connected to Elasticsearch version 6.5.0

**Comment by rwynn** [comment] 2018-12-07 21:05
I believe this was fixed in 4.12.4. Can you try latest version.

**Comment by m3hari** [comment] 2018-12-07 21:10
Alright. Can you point me what consequence does this issue case and the reasons that cause it

**Comment by rwynn** [comment] 2018-12-07 23:40
This issue was caused by a bug in the logic that shuts down the go routines and drains the channels containing each document from Mongodb. 

The commit that fixes it is this one.  

https://github.com/rwynn/gtm/commit/af24a9d5be20df7c0c81b344a37290efb3e45250

The consequence would be that Monstache would panic and exit before transmitting all documents.

**Closed** 2018-12-08 03:48 UTC
