### ISSUE TITLE
Feature request: Ability to create a  custom script to map the relate Ids

### ISSUE THREAD

**Issue by jodevsa** [rwynn/monstache#202] opened 2019-04-07 09:11 UTC
Hi @rwynn 

I'm dealing with a tree structure, were each node in the tree should trigger a change to the same collection.
Lets say i have 3 collections,  col1,col2,col3, where col3 has a reference of col2  and col2 has a reference of col1 .
tree representation:
col1-->col2-->col3
 |...........|...........|
posts   posts    posts

I also have  a collection named posts, that references  any of the the 3 collections, ie:
{
_id:
post:"hello",
col1:ObjectId(''),
col2:null,
col3:ObjectId('')
}

Representing the following relations in mongstache will result in  huge amount of indexing,

i have 33 k post, and i see around 1 million indexing attempt on mongstache when a change in col1 occur. this is due to the overlapping of relates from 3 differents collections:col1,col2,col3.

**Comment by jodevsa** [comment] 2019-04-07 10:26
Or is there any way to minimize the rate of document being re-indexed more than once (reduce overlapping)

**Comment by rwynn** [comment] 2019-04-08 15:29
Hi @jodevsa if I understand correctly this issue is caused by the transitive relationships?  Because monstache will recursively traverse the relationships, a change in col1 causes 2 + 2 + 1 relates to fire?

If that is the case then maybe would this be fixed by adding a setting to `relate` such as `max-depth` such that the relationship would only fire if the depth from the originating event is less than or equal to the given value?  

What I am thinking is that you could set `max-depth` to 1 on all the relationships to posts.  When `col1` changes posts would be synced once instead of 3 times.  The direct relationship would have a depth of 1 but the others would have depths of 2 and 3.  

Currently, what I think is happening:

- Change in `col1` (1) looks up and syncs all `posts` that have a ref to `col1` and (2) looks up all `col2` that reference `col1`.
- **For each** matching `col2` (1) all `posts` that reference the `col2` are synced and (2) all `col3` that reference the `col2` are looked up.
- **For each** matching `col3` (1) all `posts` that reference the `col3` are synced

With the addition of `max-depth` monstache would have enough information to only perform step 1.1.  It also depends on your setting for `keep-src` on the relate.  This defaults to false but if you were to set it to true, then monstache potentially do more.

**Closed** 2019-06-01 21:30 UTC
